### ISSUE TITLE
Metadata

### ISSUE THREAD

**Issue by kurtsson** [daresaydigital/dataprata#12]
Favicon and metadata. The page needs favicon and the usual meta data for link previews and such

**Comment by sebastiansoderback** [comment]
@kurtsson 

Jag skrev om title osv. och gjorde en tillhörande bild. Jag vågar dock inte göra några pull requests eller så, så jag kopierar in kod här.

![datapratalink](https://user-images.githubusercontent.com/48511098/77747392-e6b25c80-701e-11ea-807e-8505e82aec67.png)

`
<title>Lär dig kommunicera över internet med vänner och anhöriga</title>
<meta name="title" content="Lär dig kommunicera över internet med vänner och anhöriga">
<meta name="description" content="Information om hur du kan hålla kontakt med dina nära och kära under coronakrisen. ">


<meta property="og:type" content="website">
<meta property="og:url" content="https://www.dataprata.se/sv/">
<meta property="og:title" content="Lär dig kommunicera över internet med vänner och anhöriga">
<meta property="og:description" content="Information om hur du kan hålla kontakt med dina nära och kära under coronakrisen. ">
<meta property="og:image" content="">


<meta property="twitter:card" content="summary_large_image">
<meta property="twitter:url" content="https://www.dataprata.se/sv/">
<meta property="twitter:title" content="Lär dig kommunicera över internet med vänner och anhöriga">
<meta property="twitter:description" content="Information om hur du kan hålla kontakt med dina nära och kära under coronakrisen. ">
<meta property="twitter:image" content="">`

**Comment by sebastiansoderback** [comment]
Här kommer faviconen

Länk till plugin:
https://github.com/Creatiwity/gatsby-plugin-favicon

![favicon](https://user-images.githubusercontent.com/48511098/77756662-eec6c800-702f-11ea-87ce-6695e6b16bb1.png)
